services:
  # ---- Django backend ----
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: vybe-backend
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - mongodb
    restart: unless-stopped
    networks:
      - vybe-network

  postgres:
    image: postgres:17.9-alpine
    container_name: vybe-postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - vybe-network

  redis:
    image: redis:7.4.8-alpine
    container_name: vybe-redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - vybe-network

  mongodb:
    image: mongo:8.2.6
    container_name: vybe-mongodb
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - vybe-network


# creating named volumes here
# These persist data outside the container lifecycle

volumes:
  postgres_data:
  redis_data:
  mongo_data:

# --- Network ---
# A custom bridge network. All the services are on the same network
# can reach each other by service name.
networks:
  vybe-network:
    driver: bridge
