# Generated by Django 6.0.3 on 2026-04-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_avatar_url_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friend_request_cooldown',
            field=models.PositiveIntegerField(blank=True, help_text='Days before a declined sender can re-send a friend request. Null - use system default. 0 = permanent (never allow re-requests).', null=True),
        ),
    ]
