# Generated by Django 6.0.3 on 2026-05-12 18:03

from django.db import migrations, models
from django.db.models import Model


def backfill_existing_profiles_as_onboarded(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    Profile.objects.update(onboarding_complete=True)


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0004_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarding_complete',
            field=models.BooleanField(default=False,
                                      help_text='Flipped to True once the user submits the profile-completion form (or skips with defaults). Frontend gates the onboarding modal on this flag.'),
        ),
        migrations.RunPython(
            backfill_existing_profiles_as_onboarded,
            reverse_code=reverse_noop,
        ),
    ]
