# Generated by Django 6.0.3 on 2026-04-11 22:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, help_text='Post body text. Optional if media is attached.', max_length=5000)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('private', 'Private')], default='public', max_length=10)),
                ('adult_rating', models.CharField(choices=[('unclassified', 'Unclassified'), ('safe', 'Safe (author-marked)'), ('adult', 'Adult (18+)')], default='unclassified', help_text='Author-declared adult content rating. UNCLASSIFIED and SAFE posts are sent to the AI Moderator. ADULT posts skip the moderation. as of now not enforced, once DOB compliance is met, it will be done.', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', help_text="DRAFT posts are author-only and invisible to everyone else. PUBLISHED posts follow the `visibility` field's rules.", max_length=10)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Set when the post transitions to PUBLISHED. NULL while the post is a draft. Feed ordering uses this, not created_at, so a post drafted for a week and then published sorts by its publish time.', null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(help_text='The Media row holding the actual S3 object. Attached posts reference it via this FK - no duplicated fields.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.media')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.post')),
            ],
            options={
                'verbose_name': 'post media',
                'verbose_name_plural': 'post media',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at', '-id'], name='posts_post_created_a7e5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-id'], name='posts_post_author__e29b80_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['visibility', '-created_at'], name='posts_post_visibil_5a979a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'status', '-created_at'], name='posts_post_author__93064b_idx'),
        ),
        migrations.AddIndex(
            model_name='postmedia',
            index=models.Index(fields=['post', 'position'], name='posts_postm_post_id_dca632_idx'),
        ),
        migrations.AddConstraint(
            model_name='postmedia',
            constraint=models.UniqueConstraint(fields=('post', 'media'), name='unique_postmedia_post_media'),
        ),
    ]
