# Generated by Django 6.0.3 on 2026-04-07 20:29

import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendrequest',
            name='unique_friend_request',
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Least('sender', 'receiver'), django.db.models.functions.comparison.Greatest('sender', 'receiver'), name='unique_friend_pair'),
        ),
    ]
